// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2rmv8meFEaaHLdJXso2K287bXvqWsaIc',
    appId: '1:800246482110:web:bff3f0bed546d770c28aef',
    messagingSenderId: '800246482110',
    projectId: 'weather-app-ay',
    authDomain: 'weather-app-ay.firebaseapp.com',
    storageBucket: 'weather-app-ay.firebasestorage.app',
    measurementId: 'G-77MCEZ4ZYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgH_SpHUZZM8hQ3Vq0-rrc3cRb-L1OAdw',
    appId: '1:800246482110:android:2fa46ccb976d3dccc28aef',
    messagingSenderId: '800246482110',
    projectId: 'weather-app-ay',
    storageBucket: 'weather-app-ay.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2rmv8meFEaaHLdJXso2K287bXvqWsaIc',
    appId: '1:800246482110:web:2b85786f5c5682f0c28aef',
    messagingSenderId: '800246482110',
    projectId: 'weather-app-ay',
    authDomain: 'weather-app-ay.firebaseapp.com',
    storageBucket: 'weather-app-ay.firebasestorage.app',
    measurementId: 'G-V5YNXVM964',
  );
}
